motion_id = extern

"This motion is entry point for SpecialAction from other motion modules

label start

"All mofs must be enumerated here

transition playDead playDead start
transition sitDown sitDown start
transition standHigh standHigh start
transition standHighLookUp standHighLookUp start
transition rightDive rightDive start
transition leftDive leftDive start
transition leftArm leftArm start
transition rightArm rightArm start
transition preventBall preventBall start
transition bothArms bothArms start

transition getUpEngineDummy getUpEngineDummy start

"This line must be the last one
transition extern extern start
